// Class automatically generated by Dev-C++ New Class wizard

#include "point.h" // class's header file
#include "basit_konsol.h"
#include <iostream>
using namespace std;
// class constructor
Point::Point(){
	// insert your code here
}

// class destructor
Point::~Point(){
	// insert your code here
}


// returns the value of m_x
int Point::get_x()
{
	return m_x;
}


// sets the value of m_x
void Point::set_x(int x)
{
	m_x = x;
}


// returns the value of m_y
int Point::get_y()
{
	return m_y;
}


// sets the value of m_y
void Point::set_y(int y)
{
	m_y = y;
}


// returns the value of m_color
int Point::get_color()
{
	return m_color;
}


// sets the value of m_color
void Point::set_color(int color)
{
	m_color = color;
}

// No description
void Point::set_coordinates(int x , int y){
     m_x=x;
     m_y=y;
}

// No description
void Point::draw(void)
{
   gotoxy (m_x,m_y);
   cout << ".";  
}
