// Class automatically generated by Dev-C++ New Class wizard

#ifndef POINT_H
#define POINT_H

// No description
class Point
{
	public:
		// class constructor
		Point();
		// class destructor
		~Point();
		// No description
		void set_coordinates(int x , int y);
		
		void set_color(int color); // sets the value of m_color
		int get_color(); // returns the value of m_color
        void set_y(int y); // sets the value of m_y
		int get_y(); // returns the value of m_y
        void set_x(int x); // sets the value of m_x
		int get_x(); // returns the value of m_x
		// No description
		void draw(void);
	protected:
		int m_x;
		int m_y;
		int m_color;              
};

#endif // POINT_H
